package report

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/storage"
)

type Generator struct{}

func NewGenerator() *Generator {
	return &Generator{}
}

func (g *Generator) ShowSaveDialog(window fyne.Window, logContent string) {
	// Создаем диалог сохранения файла
	saveDialog := dialog.NewFileSave(func(writer fyne.URIWriteCloser, err error) {
		if err != nil {
			dialog.ShowError(err, window)
			return
		}
		if writer == nil {
			return // Пользователь отменил
		}
		
		defer writer.Close()
		
		// Генерируем полный отчет
		report := g.GenerateFullReport(logContent)
		
		// Записываем в файл
		_, err = writer.Write([]byte(report))
		if err != nil {
			dialog.ShowError(err, window)
			return
		}
		
		dialog.ShowInformation("Report Saved", 
			fmt.Sprintf("Report successfully saved to:\n%s", writer.URI().Path()), 
			window)
		
	}, window)
	
	// Настраиваем диалог
	saveDialog.SetFileName(g.generateFileName())
	saveDialog.SetFilter(storage.NewExtensionFileFilter([]string{".log", ".txt", ".json", ".html"}))
	
	// Устанавливаем начальную папку
	homeDir, _ := os.UserHomeDir()
	documentsDir := filepath.Join(homeDir, "Documents")
	if _, err := os.Stat(documentsDir); err == nil {
		listableURI, _ := storage.ListerForURI(storage.NewFileURI(documentsDir))
		saveDialog.SetLocation(listableURI)
	}
	
	saveDialog.Show()
}

func (g *Generator) generateFileName() string {
	now := time.Now()
	return fmt.Sprintf("ububu-report-%s.log", now.Format("2006-01-02-15-04"))
}

func (g *Generator) GenerateFullReport(logContent string) string {
	now := time.Now()
	
	report := fmt.Sprintf(`=====================================
🐧 Ububu 1.0 - System Optimization Report
=====================================
Date: %s
Generated by: Ububu v1.0.0
System: Ubuntu Linux

=====================================
SYSTEM INFORMATION
=====================================
%s

=====================================
OPTIMIZATION LOG
=====================================
%s

=====================================
SUMMARY
=====================================
✅ Optimization process completed
📊 Check the log above for detailed results
🔧 System has been optimized for better performance

For support and updates, visit:
https://github.com/rokoss21/ububu

=====================================
End of Report
=====================================
`, now.Format("2006-01-02 15:04:05"), g.getSystemInfo(), logContent)

	return report
}

func (g *Generator) getSystemInfo() string {
	info := "Collecting system information...\n"
	
	// Получаем информацию о системе
	if hostname, err := os.Hostname(); err == nil {
		info += fmt.Sprintf("Hostname: %s\n", hostname)
	}
	
	if user := os.Getenv("USER"); user != "" {
		info += fmt.Sprintf("User: %s\n", user)
	}
	
	// Можно добавить больше системной информации
	info += "CPU: Information not available\n"
	info += "RAM: Information not available\n"
	info += "Disk: Information not available\n"
	
	return info
}
